apiVersion: v1
kind: Service
metadata:
  name: mongodb-endpoint
spec:
  ports:
    - name: mongodb-port
      protocol: "TCP"
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-pods
