apiVersion: v1
kind: Service
metadata:
  name: kdrc-core-service
  namespace: {{.Values.namespace}}
spec:
  ports:
    - nodePort: 31301
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: kdrc-core-pods
  type: NodePort
