apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdrc-rabbitmq
spec:
  replicas: 1
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kdrc-rabbitmq-pods
  template:
    metadata:
      labels:
        app: kdrc-rabbitmq-pods
    spec:
      containers:
        - name: rabbitmq-masstransit
          image: masstransit/rabbitmq:latest
          imagePullPolicy: Always