apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  ports:
    - name: rabbitmq-web
      protocol: "TCP"
      port: 15672
      targetPort: 15672
    - name: rabbitmq-messages
      protocol: "TCP"
      port: 5672
      targetPort: 5672
  selector:
    app: kdrc-rabbitmq-pods
