apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  namespace: {{.Values.namespace}}
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/mongo
